/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthaid;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gygshwr
 */
public class BootPage extends javax.swing.JFrame {

    /**
     * Creates new form BootPage
     */
     String MasterUser = new String();
    public BootPage() {
        MasterUser = user;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    String user;
    
    public BootPage(String user) {
        MasterUser = user;
        initComponents();
        UserLabel.setText(MasterUser);
        setLocationRelativeTo(null);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BootPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Results = new javax.swing.JButton();
        Minfulness = new javax.swing.JButton();
        Take = new javax.swing.JButton();
        Positivity = new javax.swing.JButton();
        History = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        COVID = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        Hello = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(56, 175, 238));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Health Aid");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BootPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(56, 175, 238));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Health Aid");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Results.setBackground(new java.awt.Color(255, 255, 51));
        Results.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Results.setText("<html>Check<br>Results<html>");
        Results.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Results.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultsMouseClicked(evt);
            }
        });

        Minfulness.setBackground(new java.awt.Color(62, 201, 238));
        Minfulness.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Minfulness.setText("Mindfullness");
        Minfulness.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Minfulness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinfulnessMouseClicked(evt);
            }
        });

        Take.setBackground(new java.awt.Color(255, 102, 102));
        Take.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Take.setText("<html> Take A Test<html>");
        Take.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Take.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TakeMouseClicked(evt);
            }
        });

        Positivity.setBackground(new java.awt.Color(102, 255, 102));
        Positivity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Positivity.setText("Positivity");
        Positivity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Positivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PositivityMouseClicked(evt);
            }
        });

        History.setBackground(new java.awt.Color(153, 153, 255));
        History.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        History.setText("History");
        History.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryMouseClicked(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 51, 51));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setText("Log Out");
        Exit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(56, 175, 238));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Your Health Partner");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        COVID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        COVID.setForeground(new java.awt.Color(51, 153, 0));
        COVID.setText("Covid - 19 DashBoard");
        COVID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COVIDMouseClicked(evt);
            }
        });

        UserLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(51, 204, 255));
        UserLabel.setText("User");

        Hello.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Hello.setText("Welcome,");

        javax.swing.GroupLayout BootPanelLayout = new javax.swing.GroupLayout(BootPanel);
        BootPanel.setLayout(BootPanelLayout);
        BootPanelLayout.setHorizontalGroup(
            BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BootPanelLayout.createSequentialGroup()
                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BootPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BootPanelLayout.createSequentialGroup()
                                .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BootPanelLayout.createSequentialGroup()
                                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Take, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minfulness, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Positivity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(BootPanelLayout.createSequentialGroup()
                                .addComponent(COVID)
                                .addGap(44, 44, 44))))
                    .addGroup(BootPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Hello)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BootPanelLayout.setVerticalGroup(
            BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BootPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hello)
                    .addComponent(UserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(COVID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Take, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Minfulness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Positivity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinfulnessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinfulnessMouseClicked
        // TODO add your handling code here:
        Meditate M = new Meditate(MasterUser);
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MinfulnessMouseClicked

    private void PositivityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PositivityMouseClicked
        // TODO add your handling code here:
        Positivity P = new Positivity(MasterUser);
        P.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PositivityMouseClicked

    private void TakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeMouseClicked
        // TODO add your handling code here:
        
      
        BMI B = new BMI(MasterUser);
        B.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TakeMouseClicked

    private void HistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMouseClicked
        // TODO add your handling code here:
        
        History H = new History(MasterUser);
        H.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistoryMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,"Sure? You want to exit?", "Confirm LogOut",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        
        if(result == JOptionPane.YES_OPTION) {
        Login L = new Login();
        L.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_ExitMouseClicked

    private void ResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultsMouseClicked
        // TODO add your handling code here:
        
        ReportCheck R = new ReportCheck(MasterUser);
        R.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ResultsMouseClicked

    private void COVIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COVIDMouseClicked
        // TODO add your handling code here:
        Desktop d = Desktop.getDesktop();
         try {
             d.browse(new URI("https://www.covid19india.org/"));
         } catch (URISyntaxException ex) {
             Logger.getLogger(BootPage.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(BootPage.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_COVIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BootPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BootPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BootPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BootPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BootPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BootPanel;
    private javax.swing.JLabel COVID;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Hello;
    private javax.swing.JButton History;
    private javax.swing.JButton Minfulness;
    private javax.swing.JButton Positivity;
    private javax.swing.JButton Results;
    private javax.swing.JButton Take;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
