/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthaid;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author gygshwr
 */
public class Links extends javax.swing.JFrame {

    /**
     * Creates new form ReportCheck
     */
    public Links() {
        initComponents();
              setLocationRelativeTo(null);
    }

       public Links(String user) {
           initComponents();
           setLocationRelativeTo(null);

           
           
       }
       Desktop d = Desktop.getDesktop();
       
       public String decrpyt(String PIN) {
        System.out.println(PIN);
          String newPin = "";
          int len = PIN.length();

          for(int i = 0; i < len; i++) {

               switch(PIN.charAt(i)) {

                    
                    case '1': {
                         newPin = newPin + "+";
                         break;
                    }
                    case '2': {
                         newPin = newPin + "=";
                         break;
                    }
                    case '3': {
                         newPin = newPin + "-";
                         break;
                    }
                    case '4': {
                         newPin = newPin + "_";
                         break;
                    }
                    case '5': {
                         newPin = newPin + ")";
                         break;
                    }
                    case '6': {
                         newPin = newPin + "(";
                         break;
                    }
                    case '7': {
                         newPin = newPin + "*";
                         break;
                    }
                    case '8': {
                         newPin = newPin + "&";
                         break;
                    }
                    case '9': {
                         newPin = newPin + "^";
                         break;
                    }
                    case '0': {
                         newPin = newPin + "%";
                         break;
                    }

                    default: {
                         newPin = newPin + "$";
                         break;
                    }

              }
          }

          return newPin;
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Diabetes = new javax.swing.JLabel();
        COVID = new javax.swing.JLabel();
        Obesity = new javax.swing.JLabel();
        WeightLoss = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Meditation = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Welcome,");

        UserLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserLabel.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(56, 175, 238));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Health Aid");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BP.setForeground(new java.awt.Color(102, 102, 102));
        BP.setText("Blood Pressure");
        BP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BPMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(56, 175, 238));
        jLabel5.setText("Links");

        Diabetes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Diabetes.setForeground(new java.awt.Color(102, 102, 102));
        Diabetes.setText("Diabetes");
        Diabetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiabetesMouseClicked(evt);
            }
        });

        COVID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        COVID.setForeground(new java.awt.Color(102, 102, 102));
        COVID.setText("COVID - 19");
        COVID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COVIDMouseClicked(evt);
            }
        });

        Obesity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Obesity.setForeground(new java.awt.Color(102, 102, 102));
        Obesity.setText("Obesity");
        Obesity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObesityMouseClicked(evt);
            }
        });

        WeightLoss.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WeightLoss.setForeground(new java.awt.Color(102, 102, 102));
        WeightLoss.setText("Weight Loss");
        WeightLoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WeightLossMouseClicked(evt);
            }
        });

        Home.setIcon(new javax.swing.ImageIcon("E:\\Java Projects\\HealthAid\\Resources\\Home.png")); // NOI18N
        Home.setToolTipText("");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        Meditation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Meditation.setForeground(new java.awt.Color(102, 102, 102));
        Meditation.setText("Meditation");
        Meditation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeditationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Meditation)
                    .addComponent(COVID)
                    .addComponent(WeightLoss)
                    .addComponent(Obesity)
                    .addComponent(BP)
                    .addComponent(Diabetes)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(261, 261, 261)
                        .addComponent(Home)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Home)
                    .addComponent(jLabel5))
                .addGap(63, 63, 63)
                .addComponent(Diabetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Obesity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WeightLoss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Meditation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COVID)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        Login B = new Login();
        B.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void DiabetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiabetesMouseClicked
        try {
            // TODO add your handling code here:
            d.browse(new URI("https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes#:~:text=Diabetes%20is%20a%20disease%20that,to%20be%20used%20for%20energy."));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DiabetesMouseClicked

    private void BPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPMouseClicked
        try {
            // TODO add your handling code here:
            d.browse(new URI("https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BPMouseClicked

    private void ObesityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObesityMouseClicked
        try {
            // TODO add your handling code here:
            d.browse(new URI("https://www.mayoclinic.org/diseases-conditions/obesity/symptoms-causes/syc-20375742#:~:text=Obesity%20is%20a%20complex%20disease,blood%20pressure%20and%20certain%20cancers."));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ObesityMouseClicked

    private void WeightLossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WeightLossMouseClicked
        try {
            // TODO add your handling code here:
            d.browse(new URI("https://www.healthline.com/nutrition/how-to-lose-weight-as-fast-as-possible"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WeightLossMouseClicked

    private void MeditationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeditationMouseClicked
        try {
            // TODO add your handling code here:
            d.browse(new URI("https://www.mindful.org/how-to-meditate/"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_MeditationMouseClicked

    private void COVIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COVIDMouseClicked
        try {
            // TODO add your handling code here:
            d.browse(new URI("https://www.who.int/emergencies/diseases/novel-coronavirus-2019"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Links.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_COVIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Links.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Links.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Links.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Links.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Links().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BP;
    private javax.swing.JLabel COVID;
    private javax.swing.JLabel Diabetes;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Meditation;
    private javax.swing.JLabel Obesity;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel WeightLoss;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
